# Generated by Django 2.2.7 on 2020-02-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='per',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
