# Generated by Django 3.0.1 on 2020-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_notice_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalkslateuser',
            name='has_institute',
            field=models.BooleanField(default=False),
        ),
    ]
