# Generated by Django 3.0.1 on 2020-02-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_chalkslateuser_has_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=100)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ChalkSlateAdmin')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ChalkSlateAdmin')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
        ),
    ]
