# Generated by Django 3.0.1 on 2020-03-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_studentapplication_tutorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='institute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.ChalkSlateAdmin'),
        ),
    ]
