# Generated by Django 3.0.1 on 2020-06-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_tutor_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.ChalkSlateAdmin'),
        ),
    ]
